-- 코드를 입력하세요
SELECT CA.CAR_ID,CA.CAR_TYPE, ROUND(((CA.DAILY_FEE)*30)/100*(100-DI.DISCOUNT_RATE),0) FEE
FROM CAR_RENTAL_COMPANY_CAR CA LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CA.CAR_ID=HIS.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DI ON CA.CAR_TYPE=DI.CAR_TYPE
WHERE CA.CAR_ID NOT IN(SELECT CA.CAR_ID
                      FROM CAR_RENTAL_COMPANY_CAR CA LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CA.CAR_ID=HIS.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DI ON CA.CAR_TYPE=DI.CAR_TYPE
                       WHERE START_DATE<"2022-12-01" and END_DATE>"2022-11-01"
                      )
AND DI.DURATION_TYPE LIKE "30일%"
GROUP BY CA.CAR_ID 
HAVING CA.CAR_TYPE IN ("세단","SUV") and FEE>=500000 and FEE<=2000000
ORDER BY FEE DESC, CA.CAR_TYPE ASC, CA.CAR_ID DESC;
